# Generated by Django 6.0.5 on 2026-06-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(db_default=models.Func(function='now'))),
                ('updated_at', models.DateTimeField(db_default=models.Func(function='now'))),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
